server:
  port: 8081

logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: kcc
    password: 1234


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.kcc.restaurant.*